# Generated by Django 2.2.2 on 2019-07-22 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=25)),
                ('lastName', models.CharField(default='', max_length=25)),
                ('username', models.CharField(default='', max_length=25, unique=True)),
                ('password', models.CharField(default='', max_length=25)),
                ('email', models.URLField(default='')),
                ('bitsid', models.CharField(max_length=20, unique=True)),
                ('contact', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=256)),
                ('opt1', models.CharField(default='', max_length=200)),
                ('opt2', models.CharField(default='', max_length=200)),
                ('opt3', models.CharField(default='', max_length=200)),
                ('opt4', models.CharField(default='', max_length=200)),
                ('marks', models.IntegerField(default=10)),
                ('ques_no', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=256)),
                ('marks', models.IntegerField(default=10)),
                ('ques_no', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_response', models.TextField(blank=True, max_length=2000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_portal.QuestionSub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_portal.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseMCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response1', models.BooleanField(default=False)),
                ('response2', models.BooleanField(default=False)),
                ('response3', models.BooleanField(default=False)),
                ('response4', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_portal.QuestionMCQ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_portal.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=60)),
                ('start_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_portal.Candidate')),
            ],
        ),
    ]
