# Generated by Django 2.2.2 on 2019-06-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('on_review', models.BooleanField(default=False)),
                ('lastsave_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
