# Generated by Django 2.2.2 on 2019-07-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0003_auto_20190701_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
