# Generated by Django 2.2.2 on 2019-06-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0003_auto_20190626_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bitsid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
